### ISSUE TITLE
Use decompressFromEncodedURIComponent

### ISSUE THREAD

**Issue by keithlayne** [mkantor/code-from-ts-playground-url#2]
This is what the playground uses. Without it, a bunch of URLs (like the one that triggered the idea in discord) don't work.

**Comment by keithlayne** [comment]
In fact, if you look at the playground source code, follow the link in the comment to gitter, and scroll down a ways, you see the solution, courtesy of @keithlayne 😸

**Comment by keithlayne** [comment]
(to a separate problem though)

**Comment by keithlayne** [comment]
Actually, here's my version in full, do with it as you will:

```ts
import { decompressFromEncodedURIComponent } from "lz-string"

const urlFromStdin = async () => {
  process.stdin.setEncoding("utf8")
  let url = ""
  for await (const chunk of process.stdin) url += chunk
  return url
}

const main = async () => {
  // Expected invocation is `node path/to/index.js $url`.
  if (process.argv.length !== 3) {
    throw new Error(
      "This script expects a single command-line argument (the TypeScript Playground URL to decode).",
    )
  }

  const url = process.argv[2] === "-" ? await urlFromStdin() : process.argv[2]
  const code = decompressFromEncodedURIComponent(
    new URL(url).hash.replace(/^#code\//, "").trim(),
  )

  if (typeof code !== "string") {
    throw new Error(
      `Failed to decode URL. Is "${url}" a valid TypeScript Playground URL?`,
    )
  }

  console.log(code)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
```

**Comment by mkantor** [comment]
Hah, good catch. That's what I get for only testing a couple basic examples.

Thanks for the code too—I'll probably end up stealing most of it. If you want credit feel free to open a pull request and I can take it from there.

I wonder if this script should also include [that double-decoding hack](https://github.com/microsoft/TypeScript-Website/blame/5035c7ec40fb5e9c4f8b6684facca37792c7e1ae/packages/sandbox/src/getInitialCode.ts#L19-L21)? I read [the old conversation on gitter about it](https://gitter.im/Microsoft/TypeScript?at=5dc478ab9c39821509ff189a) but am still not entirely clear on why it's necessary. I guess it's to work around some excess buggy escaping that StackOverflow is/was doing? Are there other scenarios where double-decoding is useful?

I should write some tests too, but where's the fun in that?

**EDIT:** Re-reading the gitter convo, here's what I can divine: StackOverflow is (or was, I can't seem to reproduce it) replacing `+` with `%20` across the entire URL, even though that's only safe to do within the query string. Does that sound right?

**Comment by keithlayne** [comment]
Yeah, jcalz noticed the issue with his prolific SO presence. I don't think it's a real issue.

The code is yours to do with as you see fit. :)

**Comment by mkantor** [comment]
I stole/adapted your code and integrated it into`master`. Thanks again!
